# Generated by Django 4.0.4 on 2022-05-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('openingText', models.CharField(max_length=255)),
                ('releaseDate', models.CharField(max_length=255)),
            ],
        ),
    ]
