# Generated by Django 4.0.4 on 2022-05-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='releaseDate',
            field=models.DateField(),
        ),
    ]
